// Path:    src/app/opslert/page.tsx
// Purpose: Opslert dashboard — QR code generator, download, and usage guide.
//          Staff/admin page: print and stick QR in restrooms.
// Used by: Staff who need to distribute alert QR codes

'use client';

import { useState } from 'react';
import AppShell from '@/components/AppShell';
import Link from 'next/link';

// ── Alert types supported by the system ──────────────────────────
// Add new types here as the system grows
const ALERT_TYPES = [
{
  id: 'paper',
  emoji: '📄',
  label: 'กระดาษห่อผ้าอนามัย',
  desc: 'แจ้งเมื่อกระดาษใกล้หมดหรือหมดแล้ว ส่งตรงถึง LINE กลุ่มสภา',
  color: 'var(--brand)',
  bg: 'var(--brand-dim)',
  border: 'rgba(91,91,214,0.18)',
  reportPath: '/opslert/report?type=paper',
}, ] as
const;

// ── Component ─────────────────────────────────────────────────────
export default function OpslertPage() {
  const [copiedType, setCopiedType] = useState < string | null > (null);
  
  function getReportUrl(path: string): string {
    if (typeof window === 'undefined') return path;
    return `${window.location.origin}${path}`;
  }
  
  async function handleCopyUrl(type: string, path: string) {
    try {
      await navigator.clipboard.writeText(getReportUrl(path));
      setCopiedType(type);
      setTimeout(() => setCopiedType(null), 2000);
    } catch {
      // Clipboard API not available on some browsers — silently ignore
    }
  }
  
  return (
    <AppShell pageTitle="Opslert — ระบบแจ้งเตือน">

      {/* Header */}
      <div className="page-header">
        <div className="page-title">🔔 Opslert</div>
        <div className="page-subtitle">
          ระบบแจ้งเตือนสภานักเรียน — นักเรียนสแกน QR แล้วรายงานปัญหาได้ทันที
        </div>
      </div>

      {/* How it works */}
      <div className="card fade-up" style={{
        marginBottom: 20,
        background: 'var(--blue-bg)',
        border: '1.5px solid var(--blue-border)',
      }}>
        <div style={{ fontWeight: 700, fontSize: 13, color: 'var(--blue)', marginBottom: 10 }}>
          💡 ระบบทำงานอย่างไร?
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 8 }}>
          {[
            'ดาวน์โหลด QR Code แล้วพิมพ์ติดที่ห้องน้ำ',
            'นักเรียนสแกน QR → กรอกข้อมูลในหน้าเว็บ (ไม่ต้อง login)',
            'ระบบส่งแจ้งเตือนไปยัง LINE กลุ่มสภานักเรียนทันที',
            'สภาฯ รับเรื่องและดำเนินการได้อย่างรวดเร็ว',
          ].map((step, i) => (
            <div key={i} style={{ display: 'flex', gap: 10, alignItems: 'flex-start' }}>
              <div style={{
                width: 20, height: 20, borderRadius: '50%',
                background: 'var(--blue)', color: '#fff',
                display: 'flex', alignItems: 'center', justifyContent: 'center',
                fontSize: 10, fontWeight: 800, flexShrink: 0,
              }}>
                {i + 1}
              </div>
              <span style={{ fontSize: 13, color: 'var(--text-2)', lineHeight: 1.55 }}>{step}</span>
            </div>
          ))}
        </div>
      </div>

      {/* QR codes for each alert type */}
      <div className="sec-label" style={{ marginBottom: 12 }}>QR Code สำหรับแต่ละประเภท</div>

      {ALERT_TYPES.map(type => (
        <div
          key={type.id}
          className="card fade-up"
          style={{ marginBottom: 16, borderTop: `3px solid ${type.color}` }}
        >
          {/* Type header */}
          <div style={{ display: 'flex', gap: 12, alignItems: 'center', marginBottom: 20 }}>
            <div style={{
              width: 44, height: 44, borderRadius: 'var(--r-lg)',
              background: type.bg, border: `1px solid ${type.border}`,
              display: 'flex', alignItems: 'center', justifyContent: 'center',
              fontSize: 22, flexShrink: 0,
            }}>
              {type.emoji}
            </div>
            <div>
              <div style={{ fontWeight: 800, fontSize: 15 }}>{type.label}</div>
              <div style={{ fontSize: 12.5, color: 'var(--text-3)', marginTop: 3, lineHeight: 1.5 }}>
                {type.desc}
              </div>
            </div>
          </div>

          {/* QR + actions layout */}
          <div style={{ display: 'flex', gap: 20, alignItems: 'flex-start', flexWrap: 'wrap' }}>

            {/* QR image */}
            <div style={{
              padding: 12, background: '#fff',
              border: '2px solid var(--border-2)',
              borderRadius: 'var(--r-lg)',
              flexShrink: 0,
            }}>
              {/* QR generated by server-side API route — no client-side library needed */}
              <img
                src={`/api/opslert/qr?type=${type.id}`}
                alt={`QR Code — ${type.label}`}
                width={160}
                height={160}
                style={{ display: 'block', borderRadius: 4 }}
              />
            </div>

            {/* Actions */}
            <div style={{ flex: 1, minWidth: 200 }}>
              <div style={{ fontSize: 12, color: 'var(--text-3)', marginBottom: 12, lineHeight: 1.6 }}>
                สแกน QR นี้เพื่อเข้าหน้ารายงาน<br />
                หรือแชร์ลิงก์ด้านล่างได้โดยตรง
              </div>

              {/* URL preview */}
              <div style={{
                background: 'var(--surface-2)',
                border: '1px solid var(--border)',
                borderRadius: 'var(--r-md)',
                padding: '8px 12px',
                fontFamily: 'var(--font-mono)',
                fontSize: 11,
                color: 'var(--text-3)',
                marginBottom: 12,
                wordBreak: 'break-all',
              }}>
                {typeof window !== 'undefined'
                  ? `${window.location.origin}${type.reportPath}`
                  : type.reportPath}
              </div>

              <div style={{ display: 'flex', gap: 8, flexWrap: 'wrap' }}>
                {/* Download QR */}
                <a
                  href={`/api/opslert/qr?type=${type.id}&download=1`}
                  download={`opslert-${type.id}-qr.png`}
                  className="btn btn-primary btn-sm"
                >
                  ⬇️ ดาวน์โหลด QR
                </a>

                {/* Copy URL */}
                <button
                  onClick={() => void handleCopyUrl(type.id, type.reportPath)}
                  className="btn btn-ghost btn-sm"
                >
                  {copiedType === type.id ? '✅ คัดลอกแล้ว' : '📋 คัดลอก URL'}
                </button>

                {/* Open in new tab */}
                <Link
                  href={type.reportPath}
                  target="_blank"
                  rel="noopener noreferrer"
                  className="btn btn-ghost btn-sm"
                >
                  🔗 ดูหน้ารายงาน
                </Link>
              </div>
            </div>
          </div>
        </div>
      ))}

      {/* Print tip */}
      <div className="card fade-up" style={{ background: 'var(--amber-bg)', border: '1.5px solid var(--amber-border)' }}>
        <div style={{ fontWeight: 700, fontSize: 13, color: 'var(--amber)', marginBottom: 8 }}>
          🖨️ เคล็ดลับการพิมพ์
        </div>
        <div style={{ fontSize: 13, color: 'var(--text-2)', lineHeight: 1.7 }}>
          พิมพ์ขนาด A5 หรือ A4 แล้วลามิเนตเพื่อกันน้ำ ติดในตำแหน่งที่มองเห็นชัดภายในห้องน้ำ
          ควรติดใกล้บริเวณที่วางกระดาษเพื่อให้นักเรียนนึกถึงการรายงานทันที
        </div>
      </div>
    </AppShell>
  );
}